# -*- coding: utf-8 -*-
"""Pothole-Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DJc_zgAlhyyfxGTyTIrbucrNu37Ebri0
"""

import torch
from matplotlib import pyplot as plt
import cv2
import numpy as np
from sklearn import model_selection
import uuid
import os
import time
import pandas as pd

"""# New Section"""

import uuid
import os
import time
import pandas as pd

img_path = os.path.join('data','images')
labels = ['pothole']

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

!pip install -r requirements.txt

#model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
#/content/drive/MyDrive/NewPothole/runs/train/yolov5s_Results/weights/best.pt
model = torch.hub.load('ultralytics/yolov5', 'custom', path = '/content/drive/MyDrive/NewPothole/runs/train/yolov5s_Results/weights/best.pt' )

os.environ["DATASET_DIRECTORY"] = "/content/datasets"

!nvidia-smi

!pip install roboflow
from roboflow import Roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="")
project = rf.workspace("potholes-a9t9z").project("pothole-detection-5.1")
dataset = project.version(5).download("yolov5")

!python train.py --img 1280 --batch 32 --epochs 300 --data {dataset.location}/data.yaml --weights yolov5s.pt --cache --name yolov5s_Results

!python train.py --img 640 --batch 32 --epochs 300 --data {dataset.location}/data.yaml --weights /content/PotholeModel1280.pt --cache --name yolov5s_Results

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolov5/runs/train/exp3/*.jpg'):
    display(Image(filename=imageName))
    print("\n")

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolov5/runs/detect/exp3*.jpg'):
    display(Image(filename=imageName))
    print("\n")

!python detect.py --source '/content/datasets/Pothole-Detection-5.1-3/test/images' --weights '/content/yolov5/runs/train/yolov5s_Results/weights/best.pt'



from google.colab import drive
drive.mount('/content/drive')

!cp -r "/content/yolov5" "/content/drive/MyDrive/BasedOnPretrainedPothole"



!python export.py --weights /content/drive/MyDrive/NewPothole2/PotholeModel1280.pt --include tflite --int8 --img 640 --simplify